import ollama
import pandas as pd

# =====================================================
# MODEL
# =====================================================

MODEL_NAME = "llama3.2"

# =====================================================
# SYSTEM PROMPT
# =====================================================

SYSTEM_PROMPT = """
You are an Explainable AI (XAI) assistant for UAV localization.

Your job is to explain WHY localization error occurred.

The explanation should be understandable even by someone who has no Artificial Intelligence knowledge.

Rules:

1. Explain every feature in simple English.
2. Mention the actual feature value.
3. Explain HOW that feature affected localization.
4. Mention whether the feature increased or reduced localization accuracy.
5. Never mention SHAP values.
6. Never use machine learning jargon.
7. Give practical recommendations.
8. Keep the explanation professional.
9. Do NOT invent information.

Assign Risk Level:

• Low    : error < 0.30 m
• Medium : 0.30–0.80 m
• High   : >0.80 m

Output Format:

====================================================

Localization Summary

Reasons

Recommendations

Risk Level

====================================================
"""

def build_prompt(prediction, facts, recommendations):

    prompt = f"""

Predicted Localization Error

{prediction:.3f} meters

The following facts have already been verified by the Explainable AI system.

Do NOT invent any new technical reasons.

Simply convert these verified facts into a professional report.

Verified Facts

"""

    for fact in facts:

        prompt += f"""

Feature : {fact['feature']}

Value : {fact['value']}

Effect : {fact['effect']}

Explanation : {fact['reason']}

"""

    prompt += "\nRecommendations already generated by the XAI system:\n"

    for r in recommendations:

        prompt += f"- {r}\n"

    prompt += """

Instructions:

Write a UAV localization report.

Include

1. Localization Summary

2. Why localization error occurred

3. Explain each verified fact naturally.

4. Mention recommendations.

5. Mention risk level.

Do NOT invent algorithms.

Do NOT mention ORB-SLAM.

Do NOT recommend SIFT.

Do NOT recommend SURF.

Only use the verified facts above.

"""

    return prompt

# =====================================================
# GENERATE REPORT
# =====================================================

def generate_report(prediction, facts, recommendations):

    prompt = build_prompt(
        prediction,
        facts,
        recommendations
    )

    response = ollama.chat(
        model="llama3.2",
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response["message"]["content"]

# =====================================================
# TEST
# =====================================================

if __name__ == "__main__":

    dummy = pd.DataFrame({
        "Feature": [
            "orb_features",
            "blur",
            "contrast",
            "brightness",
            "class_28_percent",
            "class_180_percent",
            "mean_depth",
            "edge_density",
            "dx"
        ],

        "Value": [
            4400,
            620,
            54,
            152,
            12.8,
            1.4,
            2.10,
            0.071,
            -0.25
        ],

        "SHAP": [
            -0.19,
             0.11,
             0.08,
            -0.03,
             0.05,
             0.02,
            -0.01,
             0.03,
             0.07
        ]
    })

    from reasoning_engine import explain

    facts, recommendations = explain(dummy)

    report = generate_report(
        prediction=0.445,
        facts=facts,
        recommendations=recommendations
    )

    print(report)

    print("\n")
    print("="*70)
    print("LLM GENERATED XAI REPORT")
    print("="*70)
    print(report)
    print("="*70)